version: '3.8'

services:
  backend:
    build: ./Backend/book_hub
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/book_hub/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
