version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=supersecret
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bookhub
      - DJANGO_SETTINGS_MODULE=bookhub.settings
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookhub
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
