# Generated by Django 5.2.3 on 2025-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('publication_date', models.DateField()),
                ('description', models.TextField()),
                ('cover_image', models.URLField()),
                ('pages', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('in_stock', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
    